### PR TITLE
Feat no data component

### PR DESCRIPTION
**Pull request by ccamisoss**

### CODE REVIEW

**Comment by aialphanovatide** [comment]
Hey Cami, could you please share a screenshot of the final view of this component, as I think there is no way for me to actually see it. let me know otherwise.

**Comment by ccamisoss** [comment]
@aialphanovatide Ok I will post it on the respective monday task

**Comment by ccamisoss** [comment]
Done @aialphanovatide

**Review by daviddflix — COMMENTED** [review]
## Clarification on Component Behavior

Hey @ccamisoss,

I apologize for any confusion in my previous comment. Let me clarify the expected behavior for the component:

### Current Implementation
The component is currently displaying both messages simultaneously.

### Expected Behavior
We should be able to customize the main message of the component. Specifically:
- Only one message should be displayed at a time.
- The component should allow us to choose which message to show.

**Comment by ccamisoss** [comment]
@daviddflix I tested it and I can't replicate the bug. However, I refactorized the code in order to prevent the double message display. Let me know in case you still have trouble with the message rendering.

**Review by aialphanovatide — APPROVED** [review]
Thanks, nice work!

**Pull request merged**
