### PR TITLE
feat: enhace api monitor view

### PR DESCRIPTION
**Pull request by ccamisoss**

### CODE REVIEW

**Comment by daviddflix** [comment]
## General Feedback

Here are my main observations:

- Let's remove this part of the view as there is still no accurate data to display
   Image Reference: image


- The API endpoint name has been updated, please check the documentation and make the necessary update
   Documentation: https://newsbotv2.ngrok.io/apidocs/#/

**Comment by ccamisoss** [comment]
@daviddflix I'll comment the code in case we need it in the future then. Regarding the OpenAI endpoint, that update must be done in the server since the frontend only uses the server endpoint and not the OpenAI endpoint.
In case you need me to update the server endpoint, please create a task and assign it to me 😄

**Comment by daviddflix** [comment]
Hi Cami,

Thank you for commenting out the code instead of deleting it. That's an excellent practice as it preserves the history and context, which can be valuable for future reference.

I apologize if there was any confusion regarding the endpoint update. To clarify:

1. The change is needed on the client side, not the server side.
2. The endpoint name on the server has been updated.
3. We need to update the URL in your fetch request to match this new endpoint name.

Specifically, please update the following line in `src/views/dashboard/ApiUsage/index.js` (around line 42):

```javascript
const cgResponse = await fetch(`${config.BOTS_V2_API}/api/cg-usage`)

**Comment by ccamisoss** [comment]
Hey @daviddflix I updated the PR with 3 more commits. Applying the changes you indicated. I updated the cg endpoint, updated card styles and commented de openAi code.

**Comment by ccamisoss** [comment]
@daviddflix I corrected the card styles so they don't take up to 100% of the width. Regarding the endpoint, now it is working perfectly. I don't know what could have been the reason of the bug since I can't replicate it anymore. Anyway, the bug must be coming from the server side of the app. In case you still encounter the same error again, I'd suggest checking the endpoint manually: [https://newsbotv2.ngrok.io/coingecko/usage](url) to figure out whether it's a client or server side bug.

**Comment by aialphanovatide** [comment]
Hey Cami, 

Thanks for the changes, however the CoinGecko Component is not aligned, this should be as the previous design

**Take this mockup as the reference for the desire layout**
image

This is the current view
image

**Comment by ccamisoss** [comment]
Ohh ok my bad I thought centered was fine, I'll fix it right now @daviddflix

**Comment by ccamisoss** [comment]
@daviddflix Hey David I've commited with the new fix

**Review by daviddflix — APPROVED** [review]
nice work!

**Pull request merged**
