### PR TITLE
Feat users list

### PR DESCRIPTION
**Pull request by ccamisoss**

### CODE REVIEW

**Comment by daviddflix** [comment]
Hey Cami,

In case you're unable to resolve the issue, it's totally fine to display the data in descending order by default.

**Comment by ccamisoss** [comment]
@daviddflix I pushed the new table, let me know in case there's anything to correct

**Comment by daviddflix** [comment]
Hey @ccamisoss,

It seems there is a conflict on this path, could you please look into it?
**Path**: src/views/dashboard/ApiUsage.js

**Comment by ccamisoss** [comment]
@daviddflix I fixed the merge conflict!

**Comment by daviddflix** [comment]
## General Feedback

I have a few suggestions and requests:

**Navigation Functionality**: Please ensure that the component allows for smooth navigation between different sections or items, as this is essential for user experience.

**Sorting by Creation Date:** It would be great if we could sort the items by creation date. This feature would help users quickly identify the most recent entries.

**UI Enhancement - Header Background**: To enhance the UI, consider adding a background color to the header (first row). This will help distinguish it from the rest of the content and improve readability.

**Pagination Improvement**: Currently, there seems to be too much empty space. To address this, let's render at least 8-10 users per page. This will make better use of the available space and provide a fuller, more balanced view.

Let me know if you need any help with these changes. Once these adjustments are made, we should be good to go for merging. Thanks again for your hard work!

Reference image of the current component I see.
image

**Comment by daviddflix** [comment]
Hey @ccamisoss 

I see that you've updated the component with the suggested changes. However, the only issue is that the sorting doesn't seem to be working—I can't sort the data by creation date.

Expected Behaviour:
Create at column should allow us to sort the users by ASC and DESC.

Video reference
[sorting users.webm](https://github.com/user-attachments/assets/4bfea3f1-234d-44b1-beff-f097d0e0aeef)

**Comment by ccamisoss** [comment]
Hey @daviddflix I fixed the row repeating bug. Please try it out to make sure it is finally solved.

**Comment by daviddflix** [comment]
Hey @ccamisoss great work!

**Pull request merged**
